name: build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  release:
    types: [published]

jobs:
  build_and_test:
    strategy:
      matrix:
        os:
          - ubuntu-24.04
        rosdistro:
          - jazzy

    runs-on: ubuntu-latest

    container:
      image: ros:${{ matrix.rosdistro }}-ros-base

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Update submodules
        id: update
        run: git submodule update --remote --recursive 

      - name: Run git status
        id: status
        run: echo "::set-output name=status::$(git status -s)"   
        
      - name: Install dependencies
        run: |
          rosdep update && 
          apt-get update && 
          apt-get install -y git &&
          rosdep install --from-path . -i -y --rosdistro ${{ matrix.rosdistro }}

      - name: Install diagnostic-updater
        run: apt-get install ros-${{ matrix.rosdistro }}-diagnostic-updater

      - name: Build tests
        run: |
          . /opt/ros/${{ matrix.rosdistro }}/setup.sh && 
          colcon build
