name: build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  release:
    types: [published]

jobs:
  build_and_test:
    strategy:
      matrix:
        os:
          - ubuntu-24.04
        rosdistro:
          - jazzy

    runs-on: ubuntu-latest

    container:
      image: ros:${{ matrix.rosdistro }}-ros-base

    steps:
        
      - name: Install dependencies
        run: |
          rosdep update && 
          apt-get update && 
          apt-get install -y git &&
          rosdep install --from-path . -i -y --rosdistro ${{ matrix.rosdistro }} &&
          sudo apt -y install python3-pip &&
          pip install git+https://github.com/tier4/colcon-cargo.git --break-system-packages &&
          pip install git+https://github.com/colcon/colcon-ros-cargo.git --break-system-packages &&
          cd cargo-ament-build &&
          cargo install --path . &&
          cd ~/

      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: recursive 

      - name: Install diagnostic-updater
        run: apt-get install ros-${{ matrix.rosdistro }}-diagnostic-updater

      - name: Build tests
        run: |
          . /opt/ros/${{ matrix.rosdistro }}/setup.sh && 
          colcon build
